### ISSUE TITLE
Issue with Node Js v12

### ISSUE THREAD

**Issue by sinta3** [vitalets/google-translate-api#113]
return error when run in docker, with node version 12

2023-05-09 10:08:56 /app/node_modules/@vitalets/google-translate-api/dist/cjs/helpers.js:5
2023-05-09 10:08:56     const ip = html.match(/IP address: (.+?)<br>/)?.[1] || '';
2023-05-09 10:08:56                                                    ^
2023-05-09 10:08:56 
2023-05-09 10:08:56 SyntaxError: Unexpected token '.'
2023-05-09 10:08:56     at wrapSafe (internal/modules/cjs/loader.js:915:16)
2023-05-09 10:08:56     at Module._compile (internal/modules/cjs/loader.js:963:27)
2023-05-09 10:08:56     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2023-05-09 10:08:56     at Module.load (internal/modules/cjs/loader.js:863:32)
2023-05-09 10:08:56     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2023-05-09 10:08:56     at Module.require (internal/modules/cjs/loader.js:887:19)
2023-05-09 10:08:56     at require (internal/modules/cjs/helpers.js:74:18)
2023-05-09 10:08:56     at Object.<anonymous> (/app/node_modules/@vitalets/google-translate-api/dist/cjs/index.js:9:22)
2023-05-09 10:08:56     at Module._compile (internal/modules/cjs/loader.js:999:30)
2023-05-09 10:08:56     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by vitalets** [comment]
Node 12 is deprecated and ended security support [a year ago](https://endoflife.date/nodejs). If possible I would suggest to upgrade Node.

I will add minimal node version check to package.json.

**Comment by sinta3** [comment]
thank youu mr vitaliy!
